### PR TITLE
Remove Apply button and fix filter.Changed logic to use correct text

### LINKED ISSUE #89: Filters do not work right in out-consolegridview
In the `/GraphicalTools` directory run:

```powershell
PS> ls | ocgv
```

## In the filter box, type a period (`.`).

Nothing happens. Expected: only files with periods in their names would show.

## Try escaping the period (assuming it's expecting a regex): `\.`. 

Get an error.

## Try an underscore (`_`)

Nothing happens. Expected: only files with underscores in their names would show (`CODE_OF_CONDUCT.md`).

## Try `.md`

Nothing happens. Hit space. Filter works.
Hit backspace. Cool.

etc...

### PR DESCRIPTION
**Pull request by TylerLeonhardt**
Fixes https://github.com/PowerShell/GraphicalTools/issues/88
Fixes #89 

* No more apply button
* filterText.Changed event works properly now

### CODE REVIEW

File: src/Microsoft.PowerShell.ConsoleGuiTools/ConsoleGui.cs [hunk 1]
```diff
@@ -169,32 +169,34 @@ private void AddFilter(Window win)
...
                 ColorScheme = Colors.Base,
-                Width = Dim.Fill() - filterLabelWidth
+                Width = Dim.Fill() - filterLabel.Text.Length
             };
 
-            EventHandler<ustring> filterChanged = (object sender, ustring e) =>
+            filterField.Changed += (object sender, ustring e) =>
             {
+                // NOTE: `ustring e` seems to contain the text _before_ the added character...
+                // so we convert the `sender` into a TextField and grab the text from that.
```
Comment (TylerLeonhardt) [inline src/Microsoft.PowerShell.ConsoleGuiTools/ConsoleGui.cs:191]: this is the real change.

**Comment by TylerLeonhardt** [comment]
cc @tig
