### PR TITLE
Fixed #58 - Newlines in commands render incorrectly

### LINKED ISSUE #58: get-history | Out-ConsoleGridView with multi-line commands causes issues
Start with:

```
$someJson = @'
{
   "foo" : true
}
'@
````

Then

    get-history | Out-ConsoleGridView

Results in something ugly like this:
    
image

Powershell 7.0.

### PR DESCRIPTION
**Pull request by tig**
Per #58

### CODE REVIEW

File: src/Microsoft.PowerShell.ConsoleGuiTools/ConsoleGui.cs [hunk 1]
```diff
@@ -164,6 +164,11 @@ private static string GetPaddedString(List<string> strings, int[] colWidths, int
                     builder.Append(' ');
                 }
 
+                // Replace any newlines with encoded newline (`n)
+                // Note we can't use Environment.Newline because we don't know that the
+                // Command honors that.
+                strings[i] = strings[i].Replace("\n", "`n");
```
Comment (TylerLeonhardt) [inline src/Microsoft.PowerShell.ConsoleGuiTools/ConsoleGui.cs]: So thinking about this some more, it may be possible that the string has a carriage return and a linefeed. So in addition to what you're doing here, we should also handle that so:
```suggestion
                strings[i] = strings[i].Replace("\r\n", "`r`n");
                strings[i] = strings[i].Replace("\n", "`n");
```

This makes sure there are no lingering `\r`.

**Comment by TylerLeonhardt** [comment]
I'll give @SteveL-MSFT a chance to review since I won't be snapping a new release til probably Friday/Monday.

File: src/Microsoft.PowerShell.ConsoleGuiTools/ConsoleGui.cs (hunk 1 above)
Comment (corbob) [reply src/Microsoft.PowerShell.ConsoleGuiTools/ConsoleGui.cs]: Would it be just as good to do a replace for `\r` and another for `\n` and thus catch all of them by default?

Comment (TylerLeonhardt) [reply src/Microsoft.PowerShell.ConsoleGuiTools/ConsoleGui.cs]: Yeah that's true. I guess that would catch the off chance that there's a `\r` by itself.

Comment (tig) [reply src/Microsoft.PowerShell.ConsoleGuiTools/ConsoleGui.cs]: I concur. I've changed it to:

```csharp
                // Replace any newlines with encoded newline/linefeed (`n or `r)
                // Note we can't use Environment.Newline because we don't know that the
                // Command honors that.
                strings[i] = strings[i].Replace("\r", "`r");
                strings[i] = strings[i].Replace("\n", "`n");
```

I don't do many PRs, so I'm not sure what I'm supposed to do to push this through other than pushing it to my `master` branch... I think it's automatic?

File: README.md [hunk 2]
```diff
@@ -88,6 +88,35 @@ Get-Process | Out-ConsoleGridView
 > NOTE: If you change the code and rebuild the project, you'll need to launch a
 > _new_ PowerShell process since the dll is already loaded and can't be unloaded.
 
+### Debugging in Visual Studio Code
```
Comment (TylerLeonhardt) [inline README.md]: Thank you so much for this!!

**Comment by corbob** [comment]
> I don't do many PRs, so I'm not sure what I'm supposed to do to push this through other than pushing it to my master branch... I think it's automatic?

@tig by pushing to the branch for the PR it will automatically update the PR. A general recommendation is to create a branch for the PR and push to that branch. This allows you to keep master up to date with the upstream repository without causing issues with your PR (it also appears to be fairly common for the first few PRs to do them from master because it's not known how else to do it).

**Comment by tig** [comment]
> > I don't do many PRs, so I'm not sure what I'm supposed to do to push this through other than pushing it to my master branch... I think it's automatic?
> 
> @tig by pushing to the branch for the PR it will automatically update the PR. A general recommendation is to create a branch for the PR and push to that branch. This allows you to keep master up to date with the upstream repository without causing issues with your PR (it also appears to be fairly common for the first few PRs to do them from master because it's not known how else to do it).

Yep. I now get it. Appreciate the help.

File: src/Microsoft.PowerShell.ConsoleGuiTools/ConsoleGui.cs (hunk 1 above)
Comment (iSazonov) [reply src/Microsoft.PowerShell.ConsoleGuiTools/ConsoleGui.cs]: You should create new branch for every new PR.
