### PR TITLE
Fixes #174. Changing Filter does not undo previously marked items

### LINKED ISSUE #174: OCGV:Different Filter will "forget" all selected before
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the latest version
- [X] Search the existing issues.

### Steps to reproduce

When a filter is active at the end of choosing elements, only the elements that are included in the active filter will be returned.
eg.:
Get-Process | Out-ConsoleGridView
Check one process, eg. Word
Filter by eg.Notepad, check Notepad
When you now hit enter with the active filter for notepad, only notepad will be returned

There is only one workaround this, you have to remove the filter before hitting enter.

This bug is introduced in the newer version, as before, hitting enter in a filtered list, would gather all elements that have been checked.

### Expected behavior

```console
Word + Notepad should be returned
```

### Actual behavior

```console
Only notepad is returned
```

### Error details

```console
No Error ourput
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.2.6
PSEdition                      Core
GitCommitId                    7.2.6
OS                             Linux 5.15.56-v8+ #1575 SMP PREEMPT Fri Jul 22 20:31:26 BST 2022
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Version

0.7.2

### Visuals

_No response_

### PR DESCRIPTION
**Pull request by tig**
# PR Summary

Fixes #174.

## PR Context

This addresses #174 (changing the filter caused marked items to get unmarked) by:

- The input to the cmdlet tracks marked/unmarked items
- The list attached to the listview is now always a copy of the input list, with the filter applied (even if there's no fitler).
- Whenever mark/unmark happens in the listview, the original item in the input list is updated
- On exit, any items in the input list that are marked are provided as output

### CODE REVIEW

File: src/Microsoft.PowerShell.ConsoleGuiTools/ConsoleGui.cs [hunk 1]
```diff
@@ -109,6 +118,7 @@ private GridViewDataSource LoadData()
                 items.Add(new GridViewRow
                 {
                     DisplayString = displayString,
+                    // We use this to keep _inputSource up to date when a fitler is applied
```
Comment (andschwa) [inline src/Microsoft.PowerShell.ConsoleGuiTools/ConsoleGui.cs:121]:
```suggestion
                    // We use this to keep _inputSource up to date when a filter is applied
```

File: src/Microsoft.PowerShell.ConsoleGuiTools/ConsoleGui.cs [hunk 2]
```diff
@@ -120,9 +130,21 @@ private GridViewDataSource LoadData()
...
         {
-            List<GridViewRow> itemList = GridViewHelpers.FilterData(_itemSource.GridViewRowList, _applicationData.Filter ?? string.Empty);
-            // Set the ListView to show only the subset defined by the filter
-            _listView.Source = new GridViewDataSource(itemList);
+            // The ListView is always filled with a (filtered) copy of _inputSource.
+            // We listen for `MarkChanged` events on this filtered list and apply those changes up to _inputSource.
+
+            if (_listViewSource != null) {
+                _listViewSource.MarkChanged -= ListViewSource_MarkChanged;
+                _listViewSource = null;
```
Comment (andschwa) [inline src/Microsoft.PowerShell.ConsoleGuiTools/ConsoleGui.cs:138]: Just noting that I think we're relying on the garbage collector to dispose of the previously created `_listViewSource` here. I _think_ that's fine? If `_listViewSource` is disposable, we should do that. I'm not sure if it is though...will find out soon I guess.

File: src/Microsoft.PowerShell.ConsoleGuiTools/ConsoleGui.cs [hunk 3]
```diff
@@ -120,9 +130,21 @@ private GridViewDataSource LoadData()
...
+            }
+
+            _listViewSource = new GridViewDataSource(GridViewHelpers.FilterData(_inputSource.GridViewRowList, _applicationData.Filter ?? string.Empty));
+            _listViewSource.MarkChanged +=  ListViewSource_MarkChanged;
+            _listView.Source = _listViewSource;
+        }
+
+        private void  ListViewSource_MarkChanged (object s, GridViewDataSource.RowMarkedEventArgs a) {
+            _inputSource.GridViewRowList[a.Row.OriginalIndex].IsMarked = a.Row.IsMarked;
```
Comment (andschwa) [inline src/Microsoft.PowerShell.ConsoleGuiTools/ConsoleGui.cs:147]:
```suggestion
        private void ListViewSource_MarkChanged (object s, GridViewDataSource.RowMarkedEventArgs a)
        {
                _inputSource.GridViewRowList[a.Row.OriginalIndex].IsMarked = a.Row.IsMarked;
```

File: src/Microsoft.PowerShell.ConsoleGuiTools/GridViewDataSource.cs [hunk 4]
```diff
@@ -32,9 +32,22 @@ public void Render(ListView container, ConsoleDriver driver, bool selected, int
 
         public void SetMark(int item, bool value)
         {
+            var oldValue =  GridViewRowList[item].IsMarked;
```
Comment (andschwa) [inline src/Microsoft.PowerShell.ConsoleGuiTools/GridViewDataSource.cs:35]:
```suggestion
            var oldValue = GridViewRowList[item].IsMarked;
```

File: src/Microsoft.PowerShell.ConsoleGuiTools/GridViewDataSource.cs [hunk 5]
```diff
@@ -32,9 +32,22 @@ public void Render(ListView container, ConsoleDriver driver, bool selected, int
...
+            };
+            MarkChanged?.Invoke(this, args);
         }
 
+        public class RowMarkedEventArgs : EventArgs {
+            public GridViewRow Row { get; set;}
+            public bool OldValue { get ; set;}
+
+        }
+        public event EventHandler<RowMarkedEventArgs> MarkChanged;
```
Comment (andschwa) [inline src/Microsoft.PowerShell.ConsoleGuiTools/GridViewDataSource.cs:49]:
```suggestion
        }

        public event EventHandler<RowMarkedEventArgs> MarkChanged;
```

File: src/Microsoft.PowerShell.ConsoleGuiTools/GridViewHelpers.cs [hunk 6]
```diff
@@ -24,7 +24,7 @@ public static List<GridViewRow> FilterData(List<GridViewRow> list, string filter
 
             foreach (GridViewRow gvr in list)
             {
-                if(Regex.IsMatch(gvr.DisplayString, filter, RegexOptions.IgnoreCase))
+                if(gvr.IsMarked || Regex.IsMatch(gvr.DisplayString, filter, RegexOptions.IgnoreCase))
```
Comment (andschwa) [inline src/Microsoft.PowerShell.ConsoleGuiTools/GridViewHelpers.cs:27]:
```suggestion
                if (gvr.IsMarked || Regex.IsMatch(gvr.DisplayString, filter, RegexOptions.IgnoreCase))
```

**Review by andschwa — CHANGES_REQUESTED** [review]
Looks pretty great! Just some small style fixes (sorry) and a question on the disposability of `GridViewDataSource`.

File: src/Microsoft.PowerShell.ConsoleGuiTools/ConsoleGui.cs (hunk 2 above)
Comment (andschwa) [reply src/Microsoft.PowerShell.ConsoleGuiTools/ConsoleGui.cs:138]: Ok we're good! It is not `Disposable`, it's an implementation of `IListDataSource` (which is a simple interface with just primitives and methods) and it holds a `List<GridViewRow>` which is managed only and thus not disposable.
