### PR TITLE
Set cursor key to application mode

### LINKED ISSUE #49: Out-ConsoleGridView Makes Arrow Keys Not Working
# Steps to reproduce
1. Open the terminal (I'm using iTerm2) and run pwsh (my version is 7.0 GA)
2. Run any cmdlets and pipeline to `Out-ConsoleGridView`;<br />
```powershell
Get-ChildItem | Out-ConsoleGridView
```

3. Press `F9` and close the interface;
4. Press `up` key to quick refer the previous commands.

Now the `up` key doesn't work, I have to quit the terminal and re-open.

### PR DESCRIPTION
**Pull request by TylerLeonhardt**
Fixes #49 

Because .NET requires application mode to support Arrow key escape sequences

Esc[?1h - Set cursor key to application mode
See http://ascii-table.com/ansi-escape-sequences-vt-100.php

### CODE REVIEW

File: src/Microsoft.PowerShell.ConsoleGuiTools/ConsoleGui.cs [hunk 1]
```diff
@@ -132,6 +132,12 @@ public void Start(ApplicationData applicationData)
 
             Application.Run();
 
+            // By emitting this, we fix an issue where arrow keys don't work in the console
+            // because .NET requires application mode to support Arrow key escape sequences
+            // Esc[?1h - Set cursor key to application mode
+            // See http://ascii-table.com/ansi-escape-sequences-vt-100.php
+            Console.Write("\u001b[?1h");
```
Comment (SteveL-MSFT) [inline src/Microsoft.PowerShell.ConsoleGuiTools/ConsoleGui.cs]: Is `Close()` below used and should this be there? Or in Dispose() so that it gets emitted even if something fails?

Comment (TylerLeonhardt) [reply src/Microsoft.PowerShell.ConsoleGuiTools/ConsoleGui.cs]: Good point. Moved it to Dispose.
